spring.application.name=demo

# Environment import 
spring.config.import=optional:file:.env[.properties]

# DataSource Settings
spring.datasource.url=jdbc:postgresql://localhost:5432/ts-online
spring.datasource.username=${POSTGRE_USER_NAME}
spring.datasource.password=${POSTGRE_PASSWORD}

# JPA / Hibernate Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Logging
#logging.level.org.hibernate.SQL=DEBUG
#logging.level.org.springframework = DEBUG
#logging.level.spring.framework.security = DEBUG
logging.level.com.tsonline.app= INFO
logging.level.org.hibernate.orm.jdbc.bind=TRACE

#Image File Path
project.image = src\\main\\resources\\static\\images

# Image File Path for S3 bucket
aws.s3.bucket-name=${AWS_S3_BUCKET_NAME}
aws.s3.region=${AWS_S3_REGION}
aws.s3.access-key=${AWS_S3_ACCESS_KEY}
aws.s3.secret-key=${AWS_S3_SECRET_KEY}

#jwtToken related
spring.app.jwtSecret = A0olm9g2VvvWKTbbxSYE8Q5Nw76bHd6CoNNDsmALUbc
spring.app.jwtExpirationMs = 86400000
spring.app.jwtCookieName=TsOnlineCookie

