spring.application.name=demo

# DataSource Settings
spring.datasource.url=jdbc:postgresql://localhost:5432/ts-online
spring.datasource.username=postgres
spring.datasource.password=root

# JPA / Hibernate Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Logging
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE

#Image File Path
project.image = src\\main\\resources\\static\\images